---
http_rpc_url: "https://api.devnet.solana.com"
ws_rpc_url: "https://api.devnet.solana.com"
key_path: /tmp/payer.json
log_file: crank.log
debug_log: false
crank:
  markets:
    - name: TULIP-USDC
      market_account: 8GufnKq7YnXKhnB3WNhgy5PzU9uvHbaaRrZWQK6ixPxW
      coin_wallet: replaceme
      pc_wallet: replaceme
    - name: SLRS-USDC
      market_account: 2Gx3UfV831BAh8uQv1FKSPKS9yajfeeD8GJ4ZNb2o2YP
      coin_wallet: replaceme
      pc_wallet: replaceme
  max_wait_for_events_delay: 60
  num_accounts: 5
  events_per_worker: 5
  max_markets_per_tx: 7